### ISSUE TITLE
VM 상태 체크 관련 API 검토 필요

### ISSUE THREAD

**Issue by shydah** [osamhack2020/WEB_CodeSquare_AmongUs#16]
백엔드 서버에서 VM 상태를 체크하는 기능을 제공하기 위해, 관련 OpenStack API 등에 대한 검토가 필요합니다.

**Comment by Snowapril** [comment]
Openstack API 문서에 instance 상태 체크 관련 api 정리했습니다. 

현재 인스턴스 상태, 인스턴스 부팅 시간 및 종료 시간 등 정상 작동 확인 완료했습니다.
