### ISSUE TITLE
VM 상태 실시간 확인을 위한 프론트엔드와 백엔드 통신 방안 마련

### ISSUE THREAD

**Issue by shydah** [osamhack2020/WEB_CodeSquare_AmongUs#17]
- VM 상태 실시간 확인이 가능한지 먼저 확인이 필요합니다. (#16)
- VM 상태를 확인하기 위해 WebSocket 등 어떻게 통신할지 검토가 필요합니다.
- Socket.io 사용 여부 검토 필요

**Comment by namkyu1999** [comment]
웹소켓으로 통신하고 SockJs를 사용하면 스프링부트와 리액트간 통신이 가능할 것 같습니다.
