### ISSUE TITLE
테스트 서버용 도메인 확보

### ISSUE THREAD

**Issue by shydah** [osamhack2020/WEB_CodeSquare_AmongUs#19]
- IP주소 대신 도메인으로 접속이 가능하도록 사용할 도메인을 확보할 필요가 있어 보입니다.
- 특히 사지방에서는 `80` 포트와 `443` 포트를 제외한 거의 대부분의 포트가 막혀 있어 정상적인 개발 진행이 어렵습니다.

**Comment by namkyu1999** [comment]
프론트 단에서 amkyu1999-ide.codesquare.io 로 get 요청을 하면서 헤더로 인증서버 토큰과 더불어 백엔드단의 세션유지를 위한 jwt 토큰을 보냅니다. 백엔드에서는 두 토큰의 유효성 검사를 완료 한 후,  [openstack 서버 ip]:[특정 포트]/[유저 id] 로 요청을 보내면, 백엔드단에서 처리하기 때문에 사지방 컴과는 무관하지 않을까요?

**Comment by CirnoV** [comment]
현재 사지방 환경 상 포트 확보는 불가능해 보입니다.
막혀있지 않은 포트를 찾거나 리버스 프록시를 이용해서 접근할 수 있게 해야 할 것 같습니다.

**Comment by shydah** [comment]
> 프론트 단에서 amkyu1999-ide.codesquare.io 로 get 요청을 하면서 헤더로 인증서버 토큰과 더불어 백엔드단의 세션유지를 위한 jwt 토큰을 보냅니다. 백엔드에서는 두 토큰의 유효성 검사를 완료 한 후, [openstack 서버 ip]:[특정 포트]/[유저 id] 로 요청을 보내면, 백엔드단에서 처리하기 때문에 사지방 컴과는 무관하지 않을까요?

말씀하신 부분이 맞습니다. nginx reverse proxy가 그렇게 요청을 처리하면 됩니다. 다만 사용자가 브라우저에 `도메인:포트번호`를 치는 일은 없어야 한다는 뜻입니다.

**Comment by namkyu1999** [comment]
네네 포트번호 붙이는건 안해야할 것 같네요

**Comment by shydah** [comment]
도메인 구입 완료.
테스트 환경 구성되면 클로즈하겠습니다.
