### ISSUE TITLE
upvote / downvote  중복 문제

### ISSUE THREAD

**Issue by namkyu1999** [osamhack2020/WEB_CodeSquare_AmongUs#26]
유저가 upvote / downvote를 중복하거나 서로 교차해서 클릭할 수 없도록 구현

**Comment by shydah** [comment]
upvote를 한 상태에서 downvote를 누르면 기존 upvote가 취소되고 downvote가 반영되는 게 맞지 않을까 싶어요. 반대도 마찬가지구요.
