### ISSUE TITLE
Community Profile 작성

### ISSUE THREAD

**Issue by CirnoV** [osamhack2020/WEB_CodeSquare_AmongUs#27]
![image](https://user-images.githubusercontent.com/17797795/96330377-7721be80-108f-11eb-8392-af4fb9a39ad1.png)
https://github.com/osamhack2020/WEB_CodeSquare_AmongUs/community

오픈소스 대회이니만큼 이런거 체크해서 작성해두면 더 좋은 점수를 받을 수 있지 않을까요?

**Comment by shydah** [comment]
이게 Admin 권한이 필요한 작업이라, OSAM에 요청했고 방금 권한 부여 받았습니다.
Description은 추가했고, Repository admins accept content reports 옵션도 활성화했습니다.
