### ISSUE TITLE
QnA 최신 글 목록에 작성 날짜 없음

### ISSUE THREAD

**Issue by CirnoV** [osamhack2020/WEB_CodeSquare_AmongUs#30]
![image](https://user-images.githubusercontent.com/17797795/96371693-f0a7d280-119d-11eb-995b-fd75928363f4.png)

글을 클릭해서 들어가야 작성 날짜를 확인할 수 있기 때문에 사용에 불편함이 있을 것 같습니다.

**Comment by shydah** [comment]
날짜 추가하는 것 괜찮을 것 같습니다. 화면설계에 반영하겠습니다.

**Comment by shydah** [comment]
![질문리스트_날짜UI추가](https://user-images.githubusercontent.com/19200664/96725928-6d2ff080-13ec-11eb-91be-bd7b10e59e53.PNG)

날짜 UI 추가했습니다. "1분 전", "2시간 전" 식으로 표시하는 게 더 보기는 좋은데 개발 오버헤드가 많을 것 같아서 이번 릴리즈까지는 일단 날짜 형식으로 처리하고자 합니다. @CirnoV

**Comment by CirnoV** [comment]
> "1분 전", "2시간 전" 식으로 표시하는 게 더 보기는 좋은데 개발 오버헤드가 많을 것 같아서 이번 릴리즈까지는 일단 날짜 형식으로 처리하고자 합니다. 

https://github.com/osamhack2020/WEB_CodeSquare_AmongUs/blob/ca2bc86d175f75b773b5fff8d6f595017698778b/frontend/src/lib/utils.ts#L5-L26

https://github.com/osamhack2020/WEB_CodeSquare_AmongUs/blob/ca2bc86d175f75b773b5fff8d6f595017698778b/frontend/src/containers/qna/QnaPostViewer.tsx#L72

이미 해당 방식으로 표시하고 있어서 오버헤드는 없을 것 같습니다 😄
