### ISSUE TITLE
사용자가 새로고침 했을 때 accessToken을 갱신할 API가 없습니다.

### ISSUE THREAD

**Issue by CirnoV** [osamhack2020/WEB_CodeSquare_AmongUs#41]
https://github.com/osamhack2020/WEB_CodeSquare_AmongUs/blob/ca2bc86d175f75b773b5fff8d6f595017698778b/frontend/src/lib/api/auth.ts#L25-L26

accessToken은 스크립트로 관리되기 때문에 새로고침이나 주소창에 입력 후 이동하는 등의 서버 사이드 라우팅이 발생하면 소멸하게 됩니다. 따라서 로그인과는 별도로 httpOnly로 저장되는 refreshToken쿠키를 이용해 새로운 accessToken을 발급받아야 하는데 현재 이러한 역할을 하는 API가 없습니다.

**Comment by namkyu1999** [comment]
갱신요청안해도 자동으로 accessToken 유효성 검사하고 갱신됩니다

**Comment by CirnoV** [comment]
> 갱신요청안해도 자동으로 accessToken 유효성 검사하고 갱신됩니다

서버에서는 그렇지만 클라이언트 입장에서는 refreshToken은 httpOnly 쿠키라 스크립트로 접근 불가능하기 때문에 페이지가 이동되었을 때 해당 유저가 로그인되어 있는지 알 수 있는 방법이 없습니다. 간단하게 get 요청을 보내면 로그인 API와 동일하게 사용자 정보를 보내주는 API가 있었으면 합니다.

**Comment by namkyu1999** [comment]
그 refreshToken으로 accessToken발급하는 api는 만들겠습니다.

**Comment by namkyu1999** [comment]
그런데 지금 refreshToken은 제공 안하고 있지 않나요?

**Comment by CirnoV** [comment]
감사합니다

> 그런데 지금 refreshToken은 제공 안하고 있지 않나요?

refreshToken은 로그인 API 응답 시 set-cookie 헤더로 설정되고, 이후 API 요청 시 자동으로 cookie 헤더에 포함되는걸로 알고 있습니다.

**Comment by namkyu1999** [comment]
아 맞습니다. 지금 저도 이것저것 하다보니 정신이 없네요. 결론적으로 해당 api는 구현하겠습니다
