### ISSUE TITLE
게시글 조회 API에 사용자 추천 이력 추가

### ISSUE THREAD

**Issue by CirnoV** [osamhack2020/WEB_CodeSquare_AmongUs#45]
![image](https://user-images.githubusercontent.com/17797795/97023926-20d1e580-1591-11eb-89bb-a636767a718b.png)

사용자가 이미 추천하거나 비추천 한 글이면 이렇게 표시 하고자 합니다.

**Comment by namkyu1999** [comment]
혹시 게시물 상세 페이지 들어갈때 어떤 api 사용하시나요?

**Comment by CirnoV** [comment]
질문글은 `/board/specific/{게시글ID}` , 답변글은 `/replies/{게시글ID}` 사용합니다.
