### ISSUE TITLE
프로젝트 디렉토리 구조 개선 관련 제안

### ISSUE THREAD

**Issue by shydah** [osamhack2020/WEB_CodeSquare_AmongUs#54]
현재처럼 `docker-config`로 묶기보다는 `redis`, `mariadb` 식으로 서비스별로 디렉토리를 구성하도록 개선하면 어떨까요?
구조도 더 깔끔하고 컨테이너 단위도 명확할 것 같습니다.

**Comment by Snowapril** [comment]
.
└── WEB_CodeSquare_AmongUs
    ├── LICENSE
    ├── README.md
    ├── backend
    ├── cloud
    ├── docker-compose.yml
    ├── docs
    ├── mariadb
    └── redis

이런식으로 하자는 말씀이신가요?
