### ISSUE TITLE
accessToken을 헤더에 넣으면 리프레쉬 될 때 토큰을 제대로 반환하지 못합니다

### ISSUE THREAD

**Issue by namkyu1999** [osamhack2020/WEB_CodeSquare_AmongUs#65]
위의 이유로 accesstoken을 헤더에 넣는 것이 아닌 쿠키로 집어넣고
refreshtoken을 로컬 저장소에 저장하며 헤더에 넣는 것이 좋다고 생각합니다

**Comment by CirnoV** [comment]
왜 accessToken을 Authorization 헤더에 넣으면 토큰 반환이 되지 않는지 알 수 있을까요?

**Comment by namkyu1999** [comment]
예컨대 어떤 요청을 했을때, 응답에는 데이터가 주어져야 합니다. 근데 토큰이 만료되면 새로운 accesstoken 을 다시 줘야 하는데 기존의 바디로는 못주고 응답 헤더로 주어야 합니다. 이 방식이 번거로워서 accesstoken유효시간을 늘리는것이 좋을듯합니다

**Comment by CirnoV** [comment]
토큰 갱신을 모든 API가 아니라 `/refreshtoken` API 에서만 담당하면 되지 않을까요?

**Comment by namkyu1999** [comment]
제 코드데로 하면 어세스토큰이 만료된걸 헤더에 넣으면 제가 자동으로 토큰을 발급하도록 로직을 짜두었습니다. 근데 그 어세스토큰을 받을 바디가 없다보니 다음에 에러가 나는것 같습니다 일단 만료시가능ㄹ 늘려두긴했어요어제

**Comment by CirnoV** [comment]
네. 일단 프론트에서도 accessToken을 localStorage에 저장하는 작업을 진행해서 별 문제 없을 것으로 보입니다
