### ISSUE TITLE
FireFox에서 페이지가 표시되지 않음

### ISSUE THREAD

**Issue by CirnoV** [osamhack2020/WEB_CodeSquare_AmongUs#71]
![image](https://user-images.githubusercontent.com/17797795/97765599-134ec980-1b56-11eb-8603-ea8dfd7200c4.png)

**Comment by CirnoV** [comment]
확인 결과 테스트용으로 임의 지정한 `yyyy.MM.dd` 형태의 날짜 형식을 Chrome과 달리 FireFox에서는 인식하지 못하여 Invalid time value 오류를 내는 것으로 보임...

**Comment by shydah** [comment]
아이폰 사파리에서도 빈 화면이 표시되는 증상이 재현됩니다.

**Comment by CirnoV** [comment]
https://github.com/osamhack2020/WEB_CodeSquare_AmongUs/blob/08d9e698940d6a10fc4be157765dcb5ede3bc9e3/frontend/src/containers/HomeContainer.tsx#L538-L543

created_at을 yyyy-MM-dd 형태로 변경 예정
